# Generated by Django 5.1.6 on 2025-03-04 11:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0004_alter_invoiceitem_price'),
        ('store', '0003_remove_storeproduct_stock_storeproduct_stock_inicial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invoiceitem',
            options={'verbose_name': 'Detalle de factura', 'verbose_name_plural': 'Detalles de factura'},
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='price',
            field=models.FloatField(verbose_name='Precio unitario'),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.storeproduct', verbose_name='Producto'),
        ),
    ]
