# Generated by Django 5.1.6 on 2025-03-01 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(max_length=255)),
                ('cif', models.CharField(max_length=20, unique=True)),
                ('phone', models.IntegerField()),
                ('mail', models.EmailField(max_length=255)),
            ],
        ),
    ]
