# Generated by Django 5.1.6 on 2025-03-05 19:56

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_alter_storeproduct_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storeproduct',
            name='image',
            field=cloudinary.models.CloudinaryField(default=1, help_text='Imagen del producto', max_length=255, verbose_name='image'),
            preserve_default=False,
        ),
    ]
