# Generated by Django 5.1.6 on 2025-03-03 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='name',
            field=models.CharField(default='Delicaté', max_length=255),
            preserve_default=False,
        ),
    ]
