# Generated by Django 5.1.6 on 2025-03-03 11:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0001_initial'),
        ('type', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(verbose_name='Fecha')),
                ('payment_form', models.CharField(max_length=100, verbose_name='Forma de pago')),
                ('neto', models.FloatField(verbose_name='Importe neto')),
                ('fk_company', models.ForeignKey(db_column='fk_company', on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='company.company', verbose_name='Empresa')),
                ('fk_type', models.ForeignKey(db_column='fk_type', on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='type.type', verbose_name='Tipo')),
            ],
            options={
                'verbose_name': 'Factura',
                'verbose_name_plural': 'Facturas',
                'db_table': 'invoices',
            },
        ),
    ]
