# Generated by Django 5.1.6 on 2025-03-03 11:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BasketTemp',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField(verbose_name='Cantidad')),
                ('precio', models.FloatField(verbose_name='Precio')),
                ('temp_date', models.DateTimeField(verbose_name='Fecha')),
                ('product_id', models.ForeignKey(db_column='product_id', on_delete=django.db.models.deletion.CASCADE, related_name='basket_items', to='store.storeproduct', verbose_name='Producto')),
            ],
            options={
                'verbose_name': 'Item de cesta temporal',
                'verbose_name_plural': 'Items de cesta temporal',
                'db_table': 'basket_temp',
            },
        ),
    ]
