# Generated by Django 5.1.6 on 2025-03-04 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_fix_admin_log_user_references'),
    ]

    operations = [
    ]
