# Generated by Django 5.1.6 on 2025-03-03 11:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0001_initial'),
        ('type', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreProduct',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('iva', models.FloatField(verbose_name='IVA')),
                ('category', models.CharField(max_length=50, verbose_name='Categoría')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('description', models.CharField(max_length=250, verbose_name='Descripción')),
                ('amount', models.CharField(max_length=100, verbose_name='Cantidad')),
                ('image', models.CharField(blank=True, max_length=255, null=True, verbose_name='Imagen')),
                ('net_price', models.FloatField(verbose_name='Precio neto')),
                ('fk_company', models.ForeignKey(db_column='fk_company', on_delete=django.db.models.deletion.CASCADE, related_name='products', to='company.company', verbose_name='Empresa')),
                ('fk_type', models.ForeignKey(db_column='fk_type', on_delete=django.db.models.deletion.CASCADE, related_name='products', to='type.type', verbose_name='Tipo de comercio')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'db_table': 'store_products',
            },
        ),
    ]
