# Generated by Django 5.1.6 on 2025-03-03 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeproduct',
            name='stock',
            field=models.IntegerField(default=0, verbose_name='Stock disponible'),
        ),
    ]
