# Generated by Django 5.1.6 on 2025-03-04 20:36

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_remove_storeproduct_stock_storeproduct_stock_inicial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storeproduct',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='storeproduct',
            name='stock_inicial',
        ),
        migrations.AddField(
            model_name='storeproduct',
            name='stock',
            field=models.IntegerField(default=0, verbose_name='Stock disponible'),
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('movement_type', models.CharField(choices=[('add', 'Entrada'), ('remove', 'Salida'), ('sale', 'Venta'), ('adjustment', 'Ajuste'), ('initial', 'Stock Inicial')], max_length=20)),
                ('quantity', models.IntegerField()),
                ('previous_stock', models.IntegerField()),
                ('new_stock', models.IntegerField()),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_movements', to='store.storeproduct')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Movimiento de Stock',
                'verbose_name_plural': 'Movimientos de Stock',
                'ordering': ['-created_at'],
            },
        ),
    ]
