# Generated by Django 5.1.6 on 2025-03-06 14:37

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_alter_storeproduct_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stockmovement',
            options={'ordering': ['-created_at'], 'verbose_name': 'Movimiento de stock', 'verbose_name_plural': 'Movimientos de stock'},
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de creación'),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='movement_type',
            field=models.CharField(choices=[('initial', 'Stock inicial'), ('add', 'Añadir stock'), ('remove', 'Retirar stock')], max_length=20, verbose_name='Tipo de movimiento'),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='new_stock',
            field=models.IntegerField(verbose_name='Stock nuevo'),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='Notas'),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='previous_stock',
            field=models.IntegerField(verbose_name='Stock anterior'),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_movements', to='store.storeproduct', verbose_name='Producto'),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='quantity',
            field=models.IntegerField(verbose_name='Cantidad'),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AlterField(
            model_name='storeproduct',
            name='amount',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Cantidad (obsoleto)'),
        ),
        migrations.AlterField(
            model_name='storeproduct',
            name='stock_inicial',
            field=models.IntegerField(default=0, verbose_name='Stock inicial'),
        ),
    ]
