# Generated by Django 5.1.6 on 2025-03-03 18:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0002_initial'),
        ('store', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='baskettemp',
            name='product_id',
            field=models.ForeignKey(db_column='product_id', on_delete=django.db.models.deletion.CASCADE, related_name='basket_temp_products', to='store.storeproduct', verbose_name='Producto'),
        ),
        migrations.AlterField(
            model_name='baskettemp',
            name='user_id',
            field=models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='basket_temp_items', to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AlterModelTable(
            name='baskettemp',
            table='basket_temp_items',
        ),
    ]
