# Generated by Django 5.1.6 on 2025-03-03 19:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0003_alter_baskettemp_product_id_alter_baskettemp_user_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='baskettemp',
            options={'ordering': ['-temp_date'], 'verbose_name': 'Item de cesta temporal', 'verbose_name_plural': 'Items de cesta temporal'},
        ),
        migrations.AlterField(
            model_name='baskettemp',
            name='temp_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha'),
        ),
    ]
