# Generated by Django 5.1.6 on 2025-03-03 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0004_alter_baskettemp_options_alter_baskettemp_temp_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baskettemp',
            name='precio',
            field=models.FloatField(blank=True, null=True, verbose_name='Precio'),
        ),
    ]
