# Generated by Django 5.1.6 on 2025-03-03 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0005_alter_baskettemp_precio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baskettemp',
            name='precio',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Precio'),
        ),
    ]
