# Generated by Django 5.1.6 on 2025-03-04 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0006_alter_baskettemp_precio'),
    ]

    operations = [
        migrations.AddField(
            model_name='baskettemp',
            name='status',
            field=models.BooleanField(default=False, help_text='True si la compra fue realizada, False si está pendiente', verbose_name='Estado de la compra'),
        ),
        migrations.AlterField(
            model_name='baskettemp',
            name='precio',
            field=models.FloatField(blank=True, null=True, verbose_name='Precio'),
        ),
    ]
